version: '3.8'

services:
  jekyll-site:
    build:
      context: .
      dockerfile: deployment/Dockerfile
    ports:
      - "8080:80"
    container_name: jekyll-tailpages
    restart: unless-stopped
    environment:
      - NODE_ENV=production


